spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: FakeGrinderLeek@gmail.com
    password: Abcd123#
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
