spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: FakeGrinderLeek@gmail.com
    password: Abcd123#
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
