DROP TABLE IF EXISTS CUSTOMER_INFO;

CREATE TABLE CUSTOMER_INFO (
ID INT AUTO_INCREMENT PRIMARY_KEY,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
EMAIL_ID VARCHAR(50) NOT NULL,
PHONE_NUMBER VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
SUBSCRIPTION_PLAN VARCHAR(50) NOT NULL
);